### ISSUE TITLE
Datasource Input doesn't work

### ISSUE THREAD

**Issue by stevie-** [FUSAKLA/alertmanager-grafana-dashboard#3]
Hi, thanks for the nice dashboard.

When we import the dashboard via Grafana dashboard import and reference id `9578` (https://grafana.com/dashboards/9578) we can **not** select the prometheus datasource.

In our setup we add multiple prometheus datasources. 

Nice would be to be able to select datasource variable at top of dashboard.
Best would be to support multiple datasources and aggregate results.

Kubernetes v1.11.9
Grafana version 6.0.2
Installed via helm with chart `stable/prometheus-operator`

Thanks

**Comment by FUSAKLA** [comment]
Hi! I'm glad you like it, sorry for the late reply.

It's weird Grafana does not opt you out for the datasource. 
Adding the datasource as a visible dynamic variable seems like legit request but aggregating results from multiple datasources is currently impossible in Grafana AFAIK. When setting the datasource variable as multi-value it queries just the first one it looks like.

Only way possible is maybe the [Meta Queries datasource plugin](https://grafana.com/plugins/goshposh-metaqueries-datasource). But still there would have to be fixed number of queries probably. 

I'd suggest maybe using something like [Thanos](https://github.com/improbable-eng/thanos/issues) to aggregate data from multiple instances of Prometheus.

**Comment by FUSAKLA** [comment]
I created PR with fix, could you please try it out if it resolves your issue?
raw dashboard JSON

https://raw.githubusercontent.com/FUSAKLA/alertmanager-grafana-dashboard/8da1fc71433f8826eb09583338cfcc6eadde1212/dashboard/alertmanager-dashboard.json

**Comment by stevie-** [comment]
@FUSAKLA Thanks for the PR.

Still Grafana doesn't allow me to select a Datasource via import. I guess it's related to
`{
  "__inputs": [],` beeing empty.
https://grafana.com/docs/reference/export_import/#import-sharing-with-grafana-2-x-or-3-0

Thanks for the Datasource Selector. If I select another Datasource, instance variable is updated correctly, but I don't see any data in graphs.
Trying to debug why this is happening.

**Comment by stevie-** [comment]
I found that not all Graphs set 
`      "datasource": "$datasource",`
So they fall back to "default"

I made some graphs work, when I replace `$__interval` with f.e. "5m" or increase the range to >24h.

**Comment by FUSAKLA** [comment]
> I made some graphs work, when I replace $__interval with f.e. "5m" or increase the range to >24h.

What is your scrape interval and do you have `min_step` set for the datasource? Issue with the `$__interval` since 6.x was only for annotation queries IIRC.

> Still Grafana doesn't allow me to select a Datasource via import. I guess it's related to
{ "__inputs": [], beeing empty.
https://grafana.com/docs/reference/export_import/#import-sharing-with-grafana-2-x-or-3-0

Grafana allows to set the variable on import only for type `constant` as the docs states https://grafana.com/docs/reference/export_import/#making-a-dashboard-portable

I thing it worked somehow formerly but not sure. It's weird :/

Maybe I'd go with not setting datasource on import, defaulting to `default` datasource and allowing to change it adhoc in the dashboard.

> I found that not all Graphs set
"datasource": "$datasource",
So they fall back to "default"

Thanks for pointing this out I'll check that and fix it.

**Comment by stevie-** [comment]
> > I made some graphs work, when I replace $__interval with f.e. "5m" or increase the range to >24h.
> 
> What is your scrape interval and do you have `min_step` set for the datasource? Issue with the `$__interval` since 6.x was only for annotation queries IIRC.

Nothing set, using default (15s) scrape intervall.

> 
> > Still Grafana doesn't allow me to select a Datasource via import. I guess it's related to
> > { "__inputs": [], beeing empty.
> > https://grafana.com/docs/reference/export_import/#import-sharing-with-grafana-2-x-or-3-0
> 
> Grafana allows to set the variable on import only for type `constant` as the docs states https://grafana.com/docs/reference/export_import/#making-a-dashboard-portable
> 
> I thing it worked somehow formerly but not sure. It's weird :/
> 
> Maybe I'd go with not setting datasource on import, defaulting to `default` datasource and allowing to change it adhoc in the dashboard.
> 
Sounds good.

> > I found that not all Graphs set
> > "datasource": "$datasource",
> > So they fall back to "default"
> 
> Thanks for pointing this out I'll check that and fix it.

Thanks

**Comment by FUSAKLA** [comment]
Ok, new version hopefully fixed all you mentioned before
https://raw.githubusercontent.com/FUSAKLA/alertmanager-grafana-dashboard/6592523e0e344572e5b38b7006949df892da377a/dashboard/alertmanager-dashboard.json

To address the issue with range selector. Please try adding the `Scrape interval` setting to your Prometheus datasource. Thah should hopefully solve the issue you have.

Example: 
![image](https://user-images.githubusercontent.com/6112562/56136937-0e3a2180-5f94-11e9-8912-9ace433c629e.png)

**Comment by FUSAKLA** [comment]
Thanks for testing, it's merged and updated on the Grafana.com
